//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerlinClock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BerlinClock.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The berlin clock output for 12 hour format has same number of lamps as 
        ///the original plus a last row to denote AM/PM. Based on your input color 
        ///scheme, O indicates AM and Y indicates PM.
        /// </summary>
        internal static string str12HourDesc {
            get {
                return ResourceManager.GetString("str12HourDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The berlin clock output explicitly displaying seconds shows the same 
        ///number of lamps as the original berlin clock plus two rows at the 
        ///end for seconds. The last-but-one row has 11 lamps, each denoting 
        ///5 seconds. The last row has 4 lamps, each denoting 4 seconds..
        /// </summary>
        internal static string str24HourDesc {
            get {
                return ResourceManager.GetString("str24HourDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Please input time in hh:mm:ss format.
        /// </summary>
        internal static string strBasicBerlinInput {
            get {
                return ResourceManager.GetString("strBasicBerlinInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The Berlin clock output is: 
        ///Y = Yellow
        ///R = Red
        ///O = Off
        ///Time: .
        /// </summary>
        internal static string strBasicOutput {
            get {
                return ResourceManager.GetString("strBasicOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred...Please try again.
        /// </summary>
        internal static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input choice:
        ///1 = Basic Berlin Clock
        ///2 = Custom Berlin Clock.
        /// </summary>
        internal static string strInput {
            get {
                return ResourceManager.GetString("strInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Enter Colour Scheme. E.g. Y,R,O.
        /// </summary>
        internal static string strInputColors {
            get {
                return ResourceManager.GetString("strInputColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Enter time. E.g. 4:35PM, 23:12:34, 12/12/2017 1:10AM.
        /// </summary>
        internal static string strInputCustomTime {
            get {
                return ResourceManager.GetString("strInputCustomTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input. Please input in hh:mm:ss format. E.g. 15:04:00.
        /// </summary>
        internal static string strInvalidBasicInput {
            get {
                return ResourceManager.GetString("strInvalidBasicInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Choice.
        /// </summary>
        internal static string strInvalidChoice {
            get {
                return ResourceManager.GetString("strInvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of colors input.
        /// </summary>
        internal static string strInvalidColor {
            get {
                return ResourceManager.GetString("strInvalidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is not in valid format. Please enter valid time.
        ///  E.g. 4:35PM, 23:12:34, 12/12/2017 1:10AM.
        /// </summary>
        internal static string strInvalidCustomTime {
            get {
                return ResourceManager.GetString("strInvalidCustomTime", resourceCulture);
            }
        }
    }
}
